// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: kind.proto

package client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KindService_Get_FullMethodName        = "/kind.KindService/Get"
	KindService_Put_FullMethodName        = "/kind.KindService/Put"
	KindService_Delete_FullMethodName     = "/kind.KindService/Delete"
	KindService_RangeScan_FullMethodName  = "/kind.KindService/RangeScan"
	KindService_PrefixScan_FullMethodName = "/kind.KindService/PrefixScan"
	KindService_Query_FullMethodName      = "/kind.KindService/Query"
	KindService_Cas_FullMethodName        = "/kind.KindService/Cas"
	KindService_Watch_FullMethodName      = "/kind.KindService/Watch"
	KindService_Sync_FullMethodName       = "/kind.KindService/Sync"
)

// KindServiceClient is the client API for KindService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KindServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Record, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	RangeScan(ctx context.Context, in *RangeScanRequest, opts ...grpc.CallOption) (*RangeScanResponse, error)
	PrefixScan(ctx context.Context, in *PrefixScanRequest, opts ...grpc.CallOption) (*RangeScanResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	Cas(ctx context.Context, in *CasRequest, opts ...grpc.CallOption) (*CasResponse, error)
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncPayload], error)
}

type kindServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKindServiceClient(cc grpc.ClientConnInterface) KindServiceClient {
	return &kindServiceClient{cc}
}

func (c *kindServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Record, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Record)
	err := c.cc.Invoke(ctx, KindService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kindServiceClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, KindService_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kindServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, KindService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kindServiceClient) RangeScan(ctx context.Context, in *RangeScanRequest, opts ...grpc.CallOption) (*RangeScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeScanResponse)
	err := c.cc.Invoke(ctx, KindService_RangeScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kindServiceClient) PrefixScan(ctx context.Context, in *PrefixScanRequest, opts ...grpc.CallOption) (*RangeScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeScanResponse)
	err := c.cc.Invoke(ctx, KindService_PrefixScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kindServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, KindService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kindServiceClient) Cas(ctx context.Context, in *CasRequest, opts ...grpc.CallOption) (*CasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CasResponse)
	err := c.cc.Invoke(ctx, KindService_Cas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kindServiceClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KindService_ServiceDesc.Streams[0], KindService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KindService_WatchClient = grpc.ServerStreamingClient[WatchEvent]

func (c *kindServiceClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncPayload], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KindService_ServiceDesc.Streams[1], KindService_Sync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncRequest, SyncPayload]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KindService_SyncClient = grpc.ServerStreamingClient[SyncPayload]

// KindServiceServer is the server API for KindService service.
// All implementations must embed UnimplementedKindServiceServer
// for forward compatibility.
type KindServiceServer interface {
	Get(context.Context, *GetRequest) (*Record, error)
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	RangeScan(context.Context, *RangeScanRequest) (*RangeScanResponse, error)
	PrefixScan(context.Context, *PrefixScanRequest) (*RangeScanResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	Cas(context.Context, *CasRequest) (*CasResponse, error)
	Watch(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error
	Sync(*SyncRequest, grpc.ServerStreamingServer[SyncPayload]) error
	mustEmbedUnimplementedKindServiceServer()
}

// UnimplementedKindServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKindServiceServer struct{}

func (UnimplementedKindServiceServer) Get(context.Context, *GetRequest) (*Record, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedKindServiceServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedKindServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedKindServiceServer) RangeScan(context.Context, *RangeScanRequest) (*RangeScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RangeScan not implemented")
}
func (UnimplementedKindServiceServer) PrefixScan(context.Context, *PrefixScanRequest) (*RangeScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrefixScan not implemented")
}
func (UnimplementedKindServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedKindServiceServer) Cas(context.Context, *CasRequest) (*CasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cas not implemented")
}
func (UnimplementedKindServiceServer) Watch(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedKindServiceServer) Sync(*SyncRequest, grpc.ServerStreamingServer[SyncPayload]) error {
	return status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedKindServiceServer) mustEmbedUnimplementedKindServiceServer() {}
func (UnimplementedKindServiceServer) testEmbeddedByValue()                     {}

// UnsafeKindServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KindServiceServer will
// result in compilation errors.
type UnsafeKindServiceServer interface {
	mustEmbedUnimplementedKindServiceServer()
}

func RegisterKindServiceServer(s grpc.ServiceRegistrar, srv KindServiceServer) {
	// If the following call panics, it indicates UnimplementedKindServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KindService_ServiceDesc, srv)
}

func _KindService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KindServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KindService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KindServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KindService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KindServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KindService_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KindServiceServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KindService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KindServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KindService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KindServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KindService_RangeScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KindServiceServer).RangeScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KindService_RangeScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KindServiceServer).RangeScan(ctx, req.(*RangeScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KindService_PrefixScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrefixScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KindServiceServer).PrefixScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KindService_PrefixScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KindServiceServer).PrefixScan(ctx, req.(*PrefixScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KindService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KindServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KindService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KindServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KindService_Cas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KindServiceServer).Cas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KindService_Cas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KindServiceServer).Cas(ctx, req.(*CasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KindService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KindServiceServer).Watch(m, &grpc.GenericServerStream[WatchRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KindService_WatchServer = grpc.ServerStreamingServer[WatchEvent]

func _KindService_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KindServiceServer).Sync(m, &grpc.GenericServerStream[SyncRequest, SyncPayload]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KindService_SyncServer = grpc.ServerStreamingServer[SyncPayload]

// KindService_ServiceDesc is the grpc.ServiceDesc for KindService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KindService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kind.KindService",
	HandlerType: (*KindServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _KindService_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _KindService_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _KindService_Delete_Handler,
		},
		{
			MethodName: "RangeScan",
			Handler:    _KindService_RangeScan_Handler,
		},
		{
			MethodName: "PrefixScan",
			Handler:    _KindService_PrefixScan_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _KindService_Query_Handler,
		},
		{
			MethodName: "Cas",
			Handler:    _KindService_Cas_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _KindService_Watch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Sync",
			Handler:       _KindService_Sync_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kind.proto",
}
